In [1]:
import numpy as np

### Create an array from an iterable
Such as
- ```list```
- ```tuple```
- ```range``` iterator

Notice that not all iterables can be used to create a numpy array, such as ```set``` and ```dict```

In [2]:
arr = np.array([1,2,3,4,5]) # create a numpy array using list notation
print(arr)

[1 2 3 4 5]


In [3]:
arr = np.array((1,2,3,4,5)) # create a numpy array using a tuple, you cannot modify a tuple after its creation.
print(arr)

[1 2 3 4 5]


In [4]:
arr = np.array(range(10)) # Create range of values from 0 to 9
print(arr)

[0 1 2 3 4 5 6 7 8 9]


| Feature | List | Tuple |
| :--- | :--- | :--- |
| **Mutability** | **Mutable** (Changeable) | **Immutable** (Unchangeable) |
| **Modification** | You can add, delete, and modify elements. | You cannot add, delete, or modify elements after creation. |
| **Performance** | Slightly slower performance for iteration and lookup due to the overhead required to manage potential changes. | Slightly faster performance for iteration and lookup because their size is fixed in memory. |
| **Memory** | Uses more memory than a tuple for the same data because it needs space for internal structures that handle mutation. | Uses less memory. |

### Create an array with specified data type

In [ ]:
arr = np.array([[1,2,3], [4,5,6]], dtype='i2') # create a 2D array with int16 data type
print(arr)
print('Data Type: ' + str(arr.dtype)) # print data type of the array

[[1 2 3]
 [4 5 6]]
Data Type: int16


### Create an aray within specified range
```np.arange()``` method can be used to replace ```np.array(range())``` method

Plug in different beginning/end values and steps.

In [7]:
# np.arange(start, stop, step)
arr = np.arange(0, 32, 2)  
print(arr)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]


### Create an array of evenly spaced numbers within specified range
```np.linspace(start, stop, num_of_elements, endpoint=True, retstep=False)``` has 5 parameters:
- ```start```: start number (inclusive)
- ```stop```: end number (inclusive unless ```endpoint``` set to ```False```)
- ```num_of_elements```: number of elements contained in the array
- ```endpoint```: boolean value representing whether the ```stop``` number is inclusive or not
- ```retstep```: boolean value representing whether to return the step size

Plug in different numbers, turn the endpoint on/off (e.g., True/False)

In [5]:
arr, step_size = np.linspace(0, 5, 8, endpoint=False, retstep=True) # create array of 8 evenly spaced values from 0 to 5 (excluding 5)
print(arr)
print('The step size is ' + str(step_size))

[0.    0.625 1.25  1.875 2.5   3.125 3.75  4.375]
The step size is 0.625


### Create an array of random values of given shape
```np.random.rand()``` method returns values in the range [0,1)

```np.random.seed()``` Setting seed for reproducibility, same seed same random numbers

In [6]:
np.random.seed(123) # set seed for reproducibility
arr = np.random.rand(3, 3) # create a 3x3 array of random floats between 0 and 1
print(arr)

[[0.69646919 0.28613933 0.22685145]
 [0.55131477 0.71946897 0.42310646]
 [0.9807642  0.68482974 0.4809319 ]]


### Create an array of zeros of given shape 
- ```np.zeros()```: create array of all zeros in given shape
- ```np.zeros_like()```: create array of all zeros with the same shape and data type as the given input array

In [7]:
zeros = np.zeros((2,3)) # create a 2x3 array of zeros
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [9]:
arr = np.array([[1,2], [3,4],[5,6]], dtype=np.float32) # create a 3x2 array of float32
zeros = np.zeros_like(arr) # create an array of zeros with the same shape and data type as arr
print(arr)
print(zeros)
print('Data Type: ' + str(zeros.dtype))

[[1. 2.]
 [3. 4.]
 [5. 6.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
Data Type: float32


In [10]:
print('Shape of original array:')
print(arr.shape)
print('Shape of zeros array:')
print(zeros.shape)

Shape of original array:
(3, 2)
Shape of zeros array:
(3, 2)


### Create an array of ones of given shape 
- ```np.ones()```: create array of all ones in given shape
- ```np.ones_like()```: create array of all ones with the same shape and data type as the given input array

In [11]:
ones = np.ones((3,2)) # create a 3x2 array of ones
print(ones)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [12]:
arr = [[1,2,3], [4,5,6]] # create a 2D array
ones = np.ones_like(arr) # create an array of ones with the same shape and data type as arr
print(ones)
print('Data Type: ' + str(ones.dtype))

[[1 1 1]
 [1 1 1]]
Data Type: int64


### Create an empty array of given shape 
- ```np.empty()```: create array of empty values in given shape
- ```np.empty_like()```: create array of empty values with the same shape and data type as the given input array

Notice that the initial values are not necessarily set to zeroes.

They are just some garbage values in random memory addresses.

In [13]:
empty = np.empty((5,5)) # create a 5x5 array without initializing entries
print(empty)

[[9.68970833e-317 0.00000000e+000 1.14051258e-310 1.14051258e-310
  1.14051261e-310]
 [1.14051258e-310 1.14051258e-310 1.14051258e-310 1.14051258e-310
  1.14051258e-310]
 [1.14051258e-310 1.14051258e-310 1.14051258e-310 1.14051258e-310
  1.14051258e-310]
 [1.14051258e-310 1.14051258e-310 1.14051258e-310 1.14051258e-310
  1.14051258e-310]
 [1.14051258e-310 1.14051258e-310 1.14051258e-310 1.14051258e-310
  1.66006057e-321]]


In [14]:
arr = np.array([[1,2,3], [4,5,6]], dtype=np.int64) # create a 2D array with int64 data type
empty = np.empty_like(arr) # create an empty array with the same shape and data type as arr
print(empty)
print('Data Type: ' + str(empty.dtype))

[[1 2 3]
 [4 5 6]]
Data Type: int64


### Create an array of constant values of given shape  
- ```np.full()```: create array of constant values in given shape
- ```np.full_like()```: create array of constant values with the same shape and data type as the given input array

In [ ]:
full = np.full((4,4), 5) # create a 4x4 array filled with the value 5
print(full)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [17]:
arr = np.array([[1,2], [3,4]], dtype=np.float64) # original array
full = np.full_like(arr, 5) # fill with 5s
print(arr)
print(full)
print('Data Type: ' + str(full.dtype))

[[1. 2.]
 [3. 4.]]
[[5. 5.]
 [5. 5.]]
Data Type: float64


### Create an array in a repetitive manner
- ```np.repeat(iterable, reps, axis=None)```: repeat each element by n times
    - ```iterable```: input array
    - ```reps```: number of repetitions
    - ```axis```: which axis to repeat along, default is ```None``` which will flatten the input array and then repeat
- ```np.tile()```: repeat the whole array by n times
    - ```iterable```: input array
    - ```reps```: number of repetitions, it can be a tuple to represent repetitions along x-axis and y-axis

In [19]:
# No axis specified, then flatten the input array first and repeat
arr = [[0, 1, 2], [3, 4, 5]] # create a 2D array
print(arr) # original array
print(np.repeat(arr, 3)) # repeat each element 3 times

[[0, 1, 2], [3, 4, 5]]
[0 0 0 1 1 1 2 2 2 3 3 3 4 4 4 5 5 5]


In [ ]:
# An example of repeating along x-axis
arr = [[0, 1, 2], [3, 4, 5]]
print(np.repeat(arr, 3, axis=0)) # repeat each row 3 times, axis = 0 means rows

[[0 1 2]
 [0 1 2]
 [0 1 2]
 [3 4 5]
 [3 4 5]
 [3 4 5]]


In [32]:
# An example of repeating along y-axis
arr = [[0, 1, 2], [3, 4, 5]]
print(np.repeat(arr, 3, axis=1)) # axis=1 means y-axis, axis=0 means x-axis

[[0 0 0 1 1 1 2 2 2]
 [3 3 3 4 4 4 5 5 5]]


In [ ]:
# Repeat the whole array by a specified number of times
arr = [0, 1, 2]
print(np.tile(arr, 3)) # repeat the whole array 3 times

[0 1 2 0 1 2 0 1 2]


In [ ]:
# Repeat along specified axes
print(np.tile(arr, (2,2))) # repeat 2 times along x-axis and 2 times along y-axis

[[0 1 2 0 1 2]
 [3 4 5 3 4 5]
 [0 1 2 0 1 2]
 [3 4 5 3 4 5]]


### Create an array with given values on the diagonal

In [ ]:
np.random.seed(123) # Set seed for reproducibility
arr = np.random.rand(5,5) # Create a 5x5 array with random values
# Extract values on the diagonal
print(arr) # original array
print('Values on the diagonal: ' + str(np.diag(arr)))

[[0.69646919 0.28613933 0.22685145 0.55131477 0.71946897]
 [0.42310646 0.9807642  0.68482974 0.4809319  0.39211752]
 [0.34317802 0.72904971 0.43857224 0.0596779  0.39804426]
 [0.73799541 0.18249173 0.17545176 0.53155137 0.53182759]
 [0.63440096 0.84943179 0.72445532 0.61102351 0.72244338]]
[[0.69646919 0.28613933 0.22685145 0.55131477 0.71946897]
 [0.42310646 0.9807642  0.68482974 0.4809319  0.39211752]
 [0.34317802 0.72904971 0.43857224 0.0596779  0.39804426]
 [0.73799541 0.18249173 0.17545176 0.53155137 0.53182759]
 [0.63440096 0.84943179 0.72445532 0.61102351 0.72244338]]
Values on the diagonal: [0.69646919 0.9807642  0.43857224 0.53155137 0.72244338]


In [44]:
np.random.seed(123) # Set seed for reproducibility

# Not necessarily to be a square matrix
arr = np.random.rand(10,3)
print(arr)
# Extract values on the diagonal
print('Values on the diagonal: ' + str(np.diag(arr)))
print('Shape: ' + str(arr.shape))

[[0.69646919 0.28613933 0.22685145]
 [0.55131477 0.71946897 0.42310646]
 [0.9807642  0.68482974 0.4809319 ]
 [0.39211752 0.34317802 0.72904971]
 [0.43857224 0.0596779  0.39804426]
 [0.73799541 0.18249173 0.17545176]
 [0.53155137 0.53182759 0.63440096]
 [0.84943179 0.72445532 0.61102351]
 [0.72244338 0.32295891 0.36178866]
 [0.22826323 0.29371405 0.63097612]]
Values on the diagonal: [0.69646919 0.71946897 0.4809319 ]
Shape: (10, 3)


In [23]:
# Create a matrix given values on the diagonal
# All non-diagonal values set to zeros
arr = np.diag([1,2,3,4,5]) 
print(arr)
print('Shape: ' + str(arr.shape))

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
Shape: (5, 5)


Next [Chapter](./3.%20Inspect%20an%20Array.ipynb)