In [1]:
import numpy as np

### set seed

In [2]:
np.random.seed(123)

### set random state which is independent from the global seed

| Feature | Random Seed (Legacy) | Random State (Modern) |
| :--- | :--- | :--- |
| **Abstraction** | Initial integer input | Encapsulating object |
| **Control Level** | **Global:** Affects all future random calls. | **Local:** Creates an isolated, independent source of randomness. |
| **Reproducibility** | Guarantees global reproducibility. | Guarantees reproducibility **within the scope of the object**. |
| **Concurrency** | **Not thread-safe:** Risky in multi-threaded code as multiple threads could interfere with the global state. | **Thread-safe:** You can pass an isolated `Generator` object to each thread without interference. |

In [24]:
rs = np.random.RandomState(321) # create a random state object
rs.rand(10) # generate 10 random numbers

array([0.88594794, 0.07791236, 0.97964616, 0.24767146, 0.75288472,
       0.52667564, 0.90755375, 0.8840703 , 0.08926896, 0.5173446 ])

### generate a random sample from interval [0, 1) in a given shape

In [ ]:
rs = np.random.RandomState(321) # create a random state object
# generate a random scalar
print(rs.rand()) # generate a random scalar     

0.8859479412560747


In [ ]:
rs = np.random.RandomState(321) # create a random state object
# generate a 1-D array
print(rs.rand(3)) # generate a 1-D array          

[0.88594794 0.07791236 0.97964616]


In [33]:
rs = np.random.RandomState(321) # create a random state object

# generate a 2-D array
print(rs.rand(3,3))   # generate a 2-D array       

[[0.88594794 0.07791236 0.97964616]
 [0.24767146 0.75288472 0.52667564]
 [0.90755375 0.8840703  0.08926896]]


### generate a sample from the standard normal distribution (mean = 0, var = 1)

In [ ]:
rs = np.random.RandomState(321) # create a random state object
# generate a 2-D array from standard normal distribution
print(rs.randn(3,3)) # replace rs with np.random.randn to get different, unreproducible results

[[ 0.17251947  1.63548253  0.0373364 ]
 [-0.88414969 -1.14319226 -0.62136604]
 [-1.34864958 -0.81973103 -0.1342539 ]]


### generate an array of random integers in a given interval [low, high)

In [ ]:
rs = np.random.RandomState(321) # create a random state object
# np.ranodm.randint(low, high, size, dtype)
print(rs.randint(1, 10, 3, 'i8')) # replace rs with np.random.randn to get different, unreproducible results

[5 9 2]


### generate an array of random floating-point numbers in the interval [0.0, 1.0)

In [39]:
# the following methods are the same as np.random.rand()
print(np.random.random_sample(10))
print(np.random.random(10))
print(np.random.ranf(10))
print(np.random.sample(10))

[0.4780419  0.09899468 0.27539478 0.79442731 0.51397031 0.45329481
 0.25515125 0.1139766  0.82431305 0.3177535 ]
[0.15230703 0.21497959 0.91211032 0.04311515 0.37595241 0.31796557
 0.35403302 0.93335757 0.3885452  0.89593944]
[0.14550322 0.4903603  0.9233404  0.8013113  0.84837182 0.66544598
 0.14321914 0.11609391 0.07739594 0.38291192]
[0.14642985 0.44785731 0.35552736 0.43314193 0.80080664 0.35500568
 0.0477506  0.8495784  0.62342568 0.14159893]


### generate a random sample from a given 1-D array

In [ ]:
rs = np.random.RandomState(321) # create a random state object
# np.random.choice(iterable_or_int, size, replace=True, p=weights)
print(rs.choice(range(3), 10, replace=True, p=[0.1, 0.8, 0.1])) # use rs.choice to make an array of 10 with a range of 0-2 and specified probabilities

[1 0 2 1 1 1 2 1 0 1]


In [ ]:
rs = np.random.RandomState(321) # create a random state object
print(np.random.choice(3, 10)) #use random choice to make an array of 10 with a range of 0-2

[0 2 2 2 1 1 2 0 2 2]


In [ ]:
rs = np.random.RandomState(321) # create a random state object
print(np.random.choice([1,2,3], 10)) # use random choice to make an array of 10 from the given list

[2 2 1 3 2 3 1 2 1 3]


### shuffle an array in place

In [43]:
arr = np.array(range(10))
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [52]:
np.random.shuffle(arr) # shuffles the array in-place
print(arr)

[6 5 0 9 1 3 7 2 8 4]


### generate a permutation of an array

In [54]:
# similar to np.random.shuffle(), but it returns a copy rather than making changes in place
arr = np.array(range(10))
print('The initial array: ', arr)
print('A permutation of the array: ', np.random.permutation(arr))

The initial array:  [0 1 2 3 4 5 6 7 8 9]
A permutation of the array:  [8 1 3 6 5 9 7 2 0 4]
