In [1]:
import numpy as np

In [2]:
rs = np.random.RandomState(321) # create a random state object
arr = rs.rand(5,5) # create a 5x5 array of random numbers
print(arr)

[[0.88594794 0.07791236 0.97964616 0.24767146 0.75288472]
 [0.52667564 0.90755375 0.8840703  0.08926896 0.5173446 ]
 [0.34362129 0.21229369 0.36067344 0.27077517 0.76162502]
 [0.4780419  0.09899468 0.27539478 0.79442731 0.51397031]
 [0.45329481 0.25515125 0.1139766  0.82431305 0.3177535 ]]


### element-wise addition, subtraction, multiplication and division

In [4]:
print(arr)
print(arr + 10)


[[0.88594794 0.07791236 0.97964616 0.24767146 0.75288472]
 [0.52667564 0.90755375 0.8840703  0.08926896 0.5173446 ]
 [0.34362129 0.21229369 0.36067344 0.27077517 0.76162502]
 [0.4780419  0.09899468 0.27539478 0.79442731 0.51397031]
 [0.45329481 0.25515125 0.1139766  0.82431305 0.3177535 ]]
[[10.88594794 10.07791236 10.97964616 10.24767146 10.75288472]
 [10.52667564 10.90755375 10.8840703  10.08926896 10.5173446 ]
 [10.34362129 10.21229369 10.36067344 10.27077517 10.76162502]
 [10.4780419  10.09899468 10.27539478 10.79442731 10.51397031]
 [10.45329481 10.25515125 10.1139766  10.82431305 10.3177535 ]]


In [5]:
print(arr)
print(arr - 10)


[[0.88594794 0.07791236 0.97964616 0.24767146 0.75288472]
 [0.52667564 0.90755375 0.8840703  0.08926896 0.5173446 ]
 [0.34362129 0.21229369 0.36067344 0.27077517 0.76162502]
 [0.4780419  0.09899468 0.27539478 0.79442731 0.51397031]
 [0.45329481 0.25515125 0.1139766  0.82431305 0.3177535 ]]
[[-9.11405206 -9.92208764 -9.02035384 -9.75232854 -9.24711528]
 [-9.47332436 -9.09244625 -9.1159297  -9.91073104 -9.4826554 ]
 [-9.65637871 -9.78770631 -9.63932656 -9.72922483 -9.23837498]
 [-9.5219581  -9.90100532 -9.72460522 -9.20557269 -9.48602969]
 [-9.54670519 -9.74484875 -9.8860234  -9.17568695 -9.6822465 ]]


In [6]:
print(arr)
print(arr * 10)


[[0.88594794 0.07791236 0.97964616 0.24767146 0.75288472]
 [0.52667564 0.90755375 0.8840703  0.08926896 0.5173446 ]
 [0.34362129 0.21229369 0.36067344 0.27077517 0.76162502]
 [0.4780419  0.09899468 0.27539478 0.79442731 0.51397031]
 [0.45329481 0.25515125 0.1139766  0.82431305 0.3177535 ]]
[[8.85947941 0.77912359 9.79646157 2.47671458 7.52884718]
 [5.26675636 9.07553753 8.84070297 0.8926896  5.17344596]
 [3.43621292 2.12293694 3.60673442 2.70775173 7.61625018]
 [4.78041899 0.98994677 2.75394778 7.94427309 5.13970314]
 [4.53294809 2.55151249 1.13976602 8.24313051 3.17753499]]


In [7]:
print(arr)
print(arr / 10)

[[0.88594794 0.07791236 0.97964616 0.24767146 0.75288472]
 [0.52667564 0.90755375 0.8840703  0.08926896 0.5173446 ]
 [0.34362129 0.21229369 0.36067344 0.27077517 0.76162502]
 [0.4780419  0.09899468 0.27539478 0.79442731 0.51397031]
 [0.45329481 0.25515125 0.1139766  0.82431305 0.3177535 ]]
[[0.08859479 0.00779124 0.09796462 0.02476715 0.07528847]
 [0.05266756 0.09075538 0.08840703 0.0089269  0.05173446]
 [0.03436213 0.02122937 0.03606734 0.02707752 0.0761625 ]
 [0.04780419 0.00989947 0.02753948 0.07944273 0.05139703]
 [0.04532948 0.02551512 0.01139766 0.08243131 0.03177535]]


In [9]:
# the above operations can be performed using numpy built-in functions
# which can save memory as the output can be stored in the original array rather than assigning new memory
arr1 = np.array([1,2,3]) # create an array
print('initial arr1:', arr1)
np.add(arr1, [8,9,10], out=arr1) # perform addition and store the result in arr1
print('adding 8,9,10 to arr1:', arr1)

np.subtract(arr1, [8,9,10], out=arr1) # perform subtraction and store the result in arr1
print('subtracting 8,9,10 from arr1:', arr1)

np.multiply(arr1, [1,2,3], out=arr1) # perform multiplication and store the result in arr1
print('multiplying arr1 by [1,2,3]:', arr1)

initial arr1: [1 2 3]
adding 8,9,10 to arr1: [ 9 11 13]
subtracting 8,9,10 from arr1: [1 2 3]
multiplying arr1 by [1,2,3]: [1 4 9]


### element-wise exponentiation

In [10]:
print(np.exp(arr)) # calculate the exponential of all elements in arr

[[2.42528233 1.08102791 2.66351361 1.28103899 2.12311578]
 [1.69329382 2.47825269 2.42073278 1.09337469 1.67756711]
 [1.41004454 1.23651099 1.434295   1.31098029 2.14175378]
 [1.61291306 1.10406042 1.31705052 2.21317317 1.67191607]
 [1.573488   1.29065682 1.1207259  2.28031377 1.37403752]]


In [11]:
print(arr) #original array is unchanged

[[0.88594794 0.07791236 0.97964616 0.24767146 0.75288472]
 [0.52667564 0.90755375 0.8840703  0.08926896 0.5173446 ]
 [0.34362129 0.21229369 0.36067344 0.27077517 0.76162502]
 [0.4780419  0.09899468 0.27539478 0.79442731 0.51397031]
 [0.45329481 0.25515125 0.1139766  0.82431305 0.3177535 ]]


### element-wise logorithm

In [12]:
# natural log
print(np.log(arr))      

[[-0.12109709 -2.55217069 -0.02056384 -1.39565218 -0.28384316]
 [-0.64117041 -0.09700248 -0.1232187  -2.41610145 -0.6590461 ]
 [-1.06821512 -1.54978461 -1.01978232 -1.30646642 -0.27230095]
 [-0.73805689 -2.3126892  -1.28954965 -0.23013379 -0.66558977]
 [-0.79121257 -1.36589877 -2.1717621  -0.19320491 -1.14647936]]


In [13]:
# base 2
print(np.log2(arr))     

[[-0.17470617 -3.682004   -0.02966734 -2.01350047 -0.40949912]
 [-0.92501337 -0.139945   -0.177767   -3.48569757 -0.95080253]
 [-1.54110866 -2.23586657 -1.4712349  -1.88483263 -0.39284723]
 [-1.06479102 -3.33650524 -1.86042689 -0.33201288 -0.96024306]
 [-1.14147846 -1.97057539 -3.13319041 -0.27873576 -1.65402009]]


In [14]:
# base 10
print(np.log10(arr))    

[[-0.0525918  -1.10839365 -0.00893076 -0.60612404 -0.12327152]
 [-0.27845677 -0.04212764 -0.0535132  -1.04929953 -0.28622008]
 [-0.46391993 -0.67306291 -0.44288584 -0.56739116 -0.1182588 ]
 [-0.32053404 -1.00438816 -0.5600443  -0.09994584 -0.28906196]
 [-0.34361925 -0.5932023  -0.9431843  -0.08390782 -0.49790966]]


### element-wise square root

In [15]:
print(np.sqrt(arr))

[[0.94124808 0.27912785 0.98977076 0.49766601 0.8676893 ]
 [0.72572422 0.95265616 0.94025012 0.29877912 0.71926671]
 [0.5861922  0.4607534  0.60056094 0.52036062 0.8727113 ]
 [0.69140574 0.3146342  0.5247807  0.89130652 0.71691723]
 [0.67327172 0.50512498 0.33760421 0.90791687 0.56369628]]


### element-wise sine and cosine

In [16]:
print(np.sin(arr))

[[0.77451496 0.07783356 0.83030022 0.24514714 0.68374664]
 [0.50266227 0.78800001 0.77332588 0.08915044 0.49457398]
 [0.33689889 0.21070265 0.35290443 0.26747845 0.69009841]
 [0.46004147 0.09883307 0.27192686 0.71346244 0.49163846]
 [0.43792997 0.25239176 0.11372999 0.73408147 0.31243331]]


In [17]:
print(np.cos(arr))

[[0.63255559 0.99696637 0.55731638 0.96948588 0.72971949]
 [0.86448288 0.61567523 0.63400874 0.99601817 0.86913554]
 [0.94154083 0.9775502  0.93565938 0.96356384 0.72371554]
 [0.88789743 0.99510403 0.96231792 0.70069347 0.87079942]
 [0.89900909 0.96762513 0.9935117  0.6790614  0.9499397 ]]


### sum along a specified axis

| Axis | Dimension | Direction | Name |
| :--- | :--- | :--- | :--- |
| **Axis 0** | The first dimension | **Vertical** | **Rows** | 
| **Axis 1** | The second dimension | **Horizontal** | **Columns** | 

In [21]:
#create a 3 x 5 array
rs = np.random.RandomState(321) # create a random state object
arr = rs.rand(3,5) # create a 3x5 array of random numbers
arr

array([[0.88594794, 0.07791236, 0.97964616, 0.24767146, 0.75288472],
       [0.52667564, 0.90755375, 0.8840703 , 0.08926896, 0.5173446 ],
       [0.34362129, 0.21229369, 0.36067344, 0.27077517, 0.76162502]])

In [22]:
print(arr)
print(' ')
# sum of each column/vertical sum
print('sum of each column:', np.sum(arr, axis=0))   #axis=0 means along the column/vertical
print(' ')
# sum along the row/horizontal sum
print('sum along the row:', np.sum(arr, axis=1))    #axis=1 means along the row/horizontal

[[0.88594794 0.07791236 0.97964616 0.24767146 0.75288472]
 [0.52667564 0.90755375 0.8840703  0.08926896 0.5173446 ]
 [0.34362129 0.21229369 0.36067344 0.27077517 0.76162502]]
 
sum of each column: [1.75624487 1.19775981 2.2243899  0.60771559 2.03185433]
 
sum along the row: [2.94406263 2.92491324 1.94898862]


### Compute the min and max along a specified axis

In [23]:
print(arr)
print(' ')

# calculate along each column/vertical 
print('Column min:', np.min(arr, axis=0))# calculate min along each column/vertical min
print('Column max:', np.max(arr, axis=0)) # calculate max along each column/vertical max
print(' ')

# calculate along the row/horizontal 
print('Row min:', np.min(arr, axis=1)) # calculate min along the row/horizontal
print('Row max:', np.max(arr, axis=1))  # calculate max along the row/horizontal
print(' ')
# if axis not specified, calculate the max/min value of all elements
print('Array max:', np.max(arr))
print('Array min:', np.min(arr))

[[0.88594794 0.07791236 0.97964616 0.24767146 0.75288472]
 [0.52667564 0.90755375 0.8840703  0.08926896 0.5173446 ]
 [0.34362129 0.21229369 0.36067344 0.27077517 0.76162502]]
 
Column min: [0.34362129 0.07791236 0.36067344 0.08926896 0.5173446 ]
Column max: [0.88594794 0.90755375 0.97964616 0.27077517 0.76162502]
 
Row min: [0.07791236 0.08926896 0.21229369]
Row max: [0.97964616 0.90755375 0.76162502]
 
Array max: 0.9796461573123091
Array min: 0.07791235871612434


### Compute the indices of the min and max along a specified axis

In [24]:
print(arr)
print(' ')

# along the column - index of min and max
print('Column indices of min and max values:')
print(np.argmin(arr, axis=0))
print(np.argmax(arr, axis=0))
print(' ')
# along the row - index of min and max
print('Row indices of min and max values:')
print(np.argmin(arr, axis=1))
print(np.argmax(arr, axis=1))
print(' ')
# if axis not specified, return the index of the flattened array
print('Index of min value in flattened array:', np.argmin(arr))
print('Index of max value in flattened array:', np.argmax(arr))

[[0.88594794 0.07791236 0.97964616 0.24767146 0.75288472]
 [0.52667564 0.90755375 0.8840703  0.08926896 0.5173446 ]
 [0.34362129 0.21229369 0.36067344 0.27077517 0.76162502]]
 
Column indices of min and max values:
[2 0 2 1 1]
[0 1 0 2 2]
 
Row indices of min and max values:
[1 3 1]
[2 1 4]
 
Index of min value in flattened array: 1
Index of max value in flattened array: 2


### Compute the key statistics

Mean, Median, Standard Deviation, Variance

In [25]:

print(arr)
print(' ')
print('Array mean:', np.mean(arr))# compute the overall mean
print('Mean along column:', np.mean(arr, axis=0))   # compute the mean along the column
print('Mean along row:', np.mean(arr, axis=1))  # compute the mean along the row
print(' ')
print('Array median:', np.median(arr))# compute the overall median
print('Median along column:', np.median(arr, axis=0))  # compute the median along the column
print('Median along row:', np.median(arr, axis=1))   # compute the median along the row
print(' ')
print('Array standard deviation:', np.std(arr)) # compute the overall standard deviation
print('Standard deviation along column:', np.std(arr, axis=0))  # compute the standard deviation along the column
print('Standard deviation along row:', np.std(arr, axis=1))   # compute the standard deviation along the row
print(' ')
print('Array variance:', np.var(arr)) # compute the overall variance
print('Variance along column:', np.var(arr, axis=0))  # compute the variance along the column
print('Variance along row:', np.var(arr, axis=1))   # compute the variance along the row
# compute 5, 65, and 95 percentiles of the array
print('5, 65, and 95 percentiles:', np.percentile(arr, [5, 65, 95]))


[[0.88594794 0.07791236 0.97964616 0.24767146 0.75288472]
 [0.52667564 0.90755375 0.8840703  0.08926896 0.5173446 ]
 [0.34362129 0.21229369 0.36067344 0.27077517 0.76162502]]
 
Array mean: 0.5211976330118454
Mean along column: [0.58541496 0.39925327 0.7414633  0.20257186 0.67728478]
Mean along row: [0.58881253 0.58498265 0.38979772]
 
Array median: 0.5173445964998838
Median along column: [0.52667564 0.21229369 0.8840703  0.24767146 0.75288472]
Median along row: [0.75288472 0.52667564 0.34362129]
 
Array standard deviation: 0.30648651431682195
Standard deviation along column: [0.22526618 0.3635855  0.27207153 0.08067055 0.11315106]
Standard deviation along row: [0.35926488 0.29906929 0.19334429]
 
Array variance: 0.09393398345807549
Variance along column: [0.05074485 0.13219442 0.07402292 0.00650774 0.01280316]
Variance along row: [0.12907126 0.08944244 0.03738201]
5, 65, and 95 percentiles: [0.08586198 0.75375875 0.92918147]


### compute cumulative sum & product

In [28]:
print(arr)
print(' ')
# calculate the cumulative sums along the column/vertical
print(np.cumsum(arr, axis=0))    

print(' ')
# sum of each column/vertical sum
print('sum of each column:', np.sum(arr, axis=0))   


[[0.88594794 0.07791236 0.97964616 0.24767146 0.75288472]
 [0.52667564 0.90755375 0.8840703  0.08926896 0.5173446 ]
 [0.34362129 0.21229369 0.36067344 0.27077517 0.76162502]]
 
[[0.88594794 0.07791236 0.97964616 0.24767146 0.75288472]
 [1.41262358 0.98546611 1.86371645 0.33694042 1.27022931]
 [1.75624487 1.19775981 2.2243899  0.60771559 2.03185433]]
 
sum of each column: [1.75624487 1.19775981 2.2243899  0.60771559 2.03185433]


In [ ]:
print(arr)
print(' ')  
# calculate the cumulative sums along the row/horizontal
print(np.cumsum(arr, axis=1))    

print(' ')
# sum along the row/horizontal sum
print('sum along the row:', np.sum(arr, axis=1))    

[[0.88594794 0.07791236 0.97964616 0.24767146 0.75288472]
 [0.52667564 0.90755375 0.8840703  0.08926896 0.5173446 ]
 [0.34362129 0.21229369 0.36067344 0.27077517 0.76162502]]
 
[[0.88594794 0.9638603  1.94350646 2.19117792 2.94406263]
 [0.52667564 1.43422939 2.31829969 2.40756865 2.92491324]
 [0.34362129 0.55591499 0.91658843 1.1873636  1.94898862]]
 
sum along the row: [2.94406263 2.92491324 1.94898862]


### Element-wise comparison

In [31]:
arr1 = np.array([1,2,3,4,5]) # create an array
arr2 = np.array([5,4,3,2,1]) # create another array

In [33]:
# return an array of bools
print("Is arr1 equal to arr2?", arr1 == arr2)    # check element-wise equality
print("Is arr1 not equal to arr2?", arr1 != arr2)    # check element-wise inequality
print("Is arr1 greater than 3?", arr1 > 3)        # check element-wise greater than 3
print("Is arr1 greater than or equal to 3?", arr1 >= 3)       # check element-wise greater than or equal to 3
print("Is arr1 less than or equal to 3?", arr1 <= 3)       # check element-wise less than or equal to 3
print("Is arr1 less than 3?", arr1 < 3) # check element-wise less than 3

Is arr1 equal to arr2? [False False  True False False]
Is arr1 not equal to arr2? [ True  True False  True  True]
Is arr1 greater than 3? [False False False  True  True]
Is arr1 greater than or equal to 3? [False False  True  True  True]
Is arr1 less than or equal to 3? [ True  True  True False False]
Is arr1 less than 3? [ True  True False False False]


### Compute element-wise min and max of two arrays

In [35]:
arr1 = np.array([1, 3, 5, 7, 9]) # create an array
arr2 = np.array([0, 4, 3, 8, 7]) # create another array

print("The element-wise maximum of arr1 and arr2 is:", np.maximum(arr1, arr2)) # print element-wise maximum
print("The element-wise minimum of arr1 and arr2 is:", np.minimum(arr1, arr2)) # print element-wise minimum

The element-wise maximum of arr1 and arr2 is: [1 4 5 8 9]
The element-wise minimum of arr1 and arr2 is: [0 3 3 7 7]


### Split fractional and integral parts of a floating-point array

In [ ]:
rs = np.random.RandomState(321) # create a random state object
arr1 = rs.rand(10) * 10 # create an array of 10 random numbers scaled by 10
fr, intg = np.modf(arr1) # separate the fractional and integral parts
print('fractional: ', fr)
print('integral: ', intg)

fractional:  [0.85947941 0.77912359 0.79646157 0.47671458 0.52884718 0.26675636
 0.07553753 0.84070297 0.8926896  0.17344596]
integral:  [8. 0. 9. 2. 7. 5. 9. 8. 0. 5.]


## Array vs python lists

In [38]:
import time
# Set the number of elements
size = 10000 # 10,000 elements

# 1. Setup a standard Python List
python_list = list(range(size)) # create a list of numbers from 0 to size

# 2. Setup a NumPy Array
numpy_array = np.arange(size) # create a numpy array of numbers from 0 to size

# --- Timing the Python List (using a for loop) ---
list_result = [] # to store results
start_time = time.time() # start time
for x in python_list: # iterate through each element
    list_result.append(x / 10) # divide by 10 and store in list_result
end_time = time.time() # end time
list_duration = end_time - start_time # duration

# --- Timing the NumPy Array (using vectorization) ---
start_time = time.time() # start time
array_result = numpy_array / 10 # divide the entire array by 10
end_time = time.time() # end time
numpy_duration = end_time - start_time # duration

# --- Results ---
print(f"Python List duration: {list_duration:.6f} seconds")
print(f"NumPy Array duration: {numpy_duration:.6f} seconds")
print(f"NumPy is {list_duration / numpy_duration:.2f}x faster than a standard list.")

Python List duration: 0.002154 seconds
NumPy Array duration: 0.000517 seconds
NumPy is 4.17x faster than a standard list.
