In [2]:
import numpy as np

In [3]:
rs = np.random.RandomState(321) # create a random state object
arr = rs.rand(5,5)
print(arr)

[[0.88594794 0.07791236 0.97964616 0.24767146 0.75288472]
 [0.52667564 0.90755375 0.8840703  0.08926896 0.5173446 ]
 [0.34362129 0.21229369 0.36067344 0.27077517 0.76162502]
 [0.4780419  0.09899468 0.27539478 0.79442731 0.51397031]
 [0.45329481 0.25515125 0.1139766  0.82431305 0.3177535 ]]


### sort an array along a specified axis

In [5]:
# sort along the column and return a copy
print(np.sort(arr, axis=0))   
print(" ")
print(arr)  # original array remains unsorted

[[0.34362129 0.07791236 0.1139766  0.08926896 0.3177535 ]
 [0.45329481 0.09899468 0.27539478 0.24767146 0.51397031]
 [0.4780419  0.21229369 0.36067344 0.27077517 0.5173446 ]
 [0.52667564 0.25515125 0.8840703  0.79442731 0.75288472]
 [0.88594794 0.90755375 0.97964616 0.82431305 0.76162502]]
 
[[0.88594794 0.07791236 0.97964616 0.24767146 0.75288472]
 [0.52667564 0.90755375 0.8840703  0.08926896 0.5173446 ]
 [0.34362129 0.21229369 0.36067344 0.27077517 0.76162502]
 [0.4780419  0.09899468 0.27539478 0.79442731 0.51397031]
 [0.45329481 0.25515125 0.1139766  0.82431305 0.3177535 ]]


In [6]:
# sort along the column in place
arr.sort(axis=0)
print(arr) # now sorted along the column

[[0.34362129 0.07791236 0.1139766  0.08926896 0.3177535 ]
 [0.45329481 0.09899468 0.27539478 0.24767146 0.51397031]
 [0.4780419  0.21229369 0.36067344 0.27077517 0.5173446 ]
 [0.52667564 0.25515125 0.8840703  0.79442731 0.75288472]
 [0.88594794 0.90755375 0.97964616 0.82431305 0.76162502]]


In [5]:
# sort along the column and return a copy
print(np.sort(arr, axis=1))    

[[0.02051216 0.07577069 0.160538   0.23410999 0.32367677]
 [0.20910696 0.2196075  0.22756129 0.54927129 0.67417506]
 [0.32657277 0.56279363 0.62776371 0.63553217 0.79901529]
 [0.52581954 0.69288395 0.70838123 0.7183594  0.96520237]
 [0.54773388 0.79908087 0.81701677 0.97694313 0.98800108]]


In [7]:
# sort along the row in place
arr.sort(axis=1)    
print(arr)

[[0.07791236 0.08926896 0.1139766  0.3177535  0.34362129]
 [0.09899468 0.24767146 0.27539478 0.45329481 0.51397031]
 [0.21229369 0.27077517 0.36067344 0.4780419  0.5173446 ]
 [0.25515125 0.52667564 0.75288472 0.79442731 0.8840703 ]
 [0.76162502 0.82431305 0.88594794 0.90755375 0.97964616]]


### compute the indices that would sort an array along a specified axis

In [8]:
rs = np.random.RandomState(321) # create a random state object
arr = rs.rand(5,5)
print(arr)

[[0.88594794 0.07791236 0.97964616 0.24767146 0.75288472]
 [0.52667564 0.90755375 0.8840703  0.08926896 0.5173446 ]
 [0.34362129 0.21229369 0.36067344 0.27077517 0.76162502]
 [0.4780419  0.09899468 0.27539478 0.79442731 0.51397031]
 [0.45329481 0.25515125 0.1139766  0.82431305 0.3177535 ]]


In [ ]:
# along the column - return the indices that would sort the array
print(np.argsort(arr, axis=0))

[[2 0 4 1 4]
 [4 3 3 0 3]
 [3 2 2 2 1]
 [1 4 1 3 0]
 [0 1 0 4 2]]


In [10]:
# along the row - return the indices that would sort the array
print(np.argsort(arr, axis=1))

[[1 3 4 0 2]
 [3 4 0 2 1]
 [1 3 0 2 4]
 [1 2 0 4 3]
 [2 1 4 0 3]]


In [11]:
# if axis=None, return the indices of a flattened array
print(np.argsort(arr, axis=None))

[ 1  8 16 22 11  3 21 13 17 24 10 12 20 15 19  9  5  4 14 18 23  7  0  6
  2]
