In [1]:
import numpy as np

This notebook demonstrates various NumPy array slicing and indexing techniques, including basic indexing, slicing, boolean indexing, fancy indexing, and conditional selection.

In [ ]:
# Create a 10x10 array with values from 0 to 99
arr = np.array(range(100)).reshape((10,10))
print(arr)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


### select an element by row and column indices

In [ ]:
# Select the element at row 5, column 5 using nested list-style indexing
print(arr[5][5])
# Or more concisely using comma-separated indices
print(arr[5,5])

55
55


### indexing with slicing

In [ ]:
# Slice the array: rows 1 to 3 (exclusive), columns 4 to 6 (exclusive)
print(arr[1:3, 4:6])

[[14 15]
 [24 25]]


In [ ]:
# Create a 4D array (2x2x2x2) and use ellipsis to slice the first dimension
arr = np.array(range(16)).reshape(2,2,2,2)
# Equivalent to arr[0,:,:,:]
print(arr[0, ...])

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


### assign a scalar to a slice by broadcasting

In [ ]:
arr[1:3,:] = 100    # set rows 1 and 2 to 100
arr[:,8:] = 100 # set last two columns to 100
print(arr)

[[  0   1   2   3   4   5   6   7 100 100]
 [100 100 100 100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100 100 100 100]
 [ 30  31  32  33  34  35  36  37 100 100]
 [ 40  41  42  43  44  45  46  47 100 100]
 [ 50  51  52  53  54  55  56  57 100 100]
 [ 60  61  62  63  64  65  66  67 100 100]
 [ 70  71  72  73  74  75  76  77 100 100]
 [ 80  81  82  83  84  85  86  87 100 100]
 [ 90  91  92  93  94  95  96  97 100 100]]


### boolean indexing

In [10]:
arr1 = np.arange(25).reshape((5,5)) # 5x5 array
bools = np.array([True, True, False, True, False]) # boolean index array
print(arr1)
print("Boolean Indexing Result:")
print(arr1[bools])
print(arr1[bools].shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Boolean Indexing Result:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [15 16 17 18 19]]
(3, 5)


In [13]:
print(arr1)
print("Boolean Negate Indexing Result:")
# negate the condition
print(arr1[~bools])    

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Boolean Negate Indexing Result:
[[10 11 12 13 14]
 [20 21 22 23 24]]


In [ ]:
arr2 = np.array([1,2,3,4,5]) # sample array for condition-based indexing
# multiple conditions
print(arr2<2) # print boolean array where condition is met
print(arr2>4) # print boolean array where condition is met
print(arr1[(arr2<2) | (arr2>4)])    # select rows in arr1 where arr2 < 2 or arr2 > 4

[ True False False False False]
[False False False False  True]
[[ 0  1  2  3  4]
 [20 21 22 23 24]]


### fancy indexing

In [18]:
rs = np.random.RandomState(321) # create a random state object
arr = rs.rand(10,10)
print(arr)

[[0.88594794 0.07791236 0.97964616 0.24767146 0.75288472 0.52667564
  0.90755375 0.8840703  0.08926896 0.5173446 ]
 [0.34362129 0.21229369 0.36067344 0.27077517 0.76162502 0.4780419
  0.09899468 0.27539478 0.79442731 0.51397031]
 [0.45329481 0.25515125 0.1139766  0.82431305 0.3177535  0.15230703
  0.21497959 0.91211032 0.04311515 0.37595241]
 [0.31796557 0.35403302 0.93335757 0.3885452  0.89593944 0.14550322
  0.4903603  0.9233404  0.8013113  0.84837182]
 [0.66544598 0.14321914 0.11609391 0.07739594 0.38291192 0.14642985
  0.44785731 0.35552736 0.43314193 0.80080664]
 [0.35500568 0.0477506  0.8495784  0.62342568 0.14159893 0.99707981
  0.43055091 0.92260123 0.23040647 0.51684848]
 [0.74245013 0.08755963 0.20380958 0.5563697  0.0069422  0.35661115
  0.84971676 0.09130986 0.1303308  0.81932886]
 [0.71126234 0.51564004 0.32849226 0.61874605 0.82843957 0.51893094
  0.65146536 0.84698965 0.47796507 0.72038246]
 [0.7057224  0.77446474 0.15782307 0.10043526 0.63983793 0.12224158
  0.54364296 

In [19]:
# select arr[3,3], arr[1,2], arr[2,1]
print(arr[[3,1,2], [3,2,1]])       

[0.3885452  0.36067344 0.25515125]


In [20]:
# select rows 3,1,2 and columns 6,4,8 
print(arr[[3,1,2]][:, [6,4,8]])    

[[0.4903603  0.89593944 0.8013113 ]
 [0.09899468 0.76162502 0.79442731]
 [0.21497959 0.3177535  0.04311515]]


### dimension inference

In [25]:
# dimension inference using any negative number (usually -1)
arr = np.array(range(16)) # 1D array with values from 0 to 15
print(arr)
print(arr.shape)
print(" ")
arr = arr.reshape((4,-1)) # reshape to 4 rows and infer columns
print(arr)
print(arr.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
(16,)
 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
(4, 4)


### find elements/indices by conditions

In [26]:
arr = np.arange(16).reshape(4,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [27]:
# find the elements greater than 5 and return a flattened array
print(arr[arr>5])    # or arr[np.where(arr>5)]

[ 6  7  8  9 10 11 12 13 14 15]


In [ ]:
# return values based on conditions 
# np.where(condition, true_return, false_return)
print(np.where(arr>5, -1, 10)) # if element > 5 return -1 else return 10

[[10 10 10 10]
 [10 10 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]]


In [29]:
# find the indices of the elements on conditions
print(np.argwhere(arr>5))

[[1 2]
 [1 3]
 [2 0]
 [2 1]
 [2 2]
 [2 3]
 [3 0]
 [3 1]
 [3 2]
 [3 3]]
